---
title: "growth_rate"
author: "Martin"
date: "3/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(reshape2)

```

```{r}
sp_data <- mpxtractor::read_spectramax_data(file = "../inst/extdata/spectraMax_2ndplate.txt")
sp_data_layout <- mpxtractor::read_layout_files(sp_data, reader_type = "spectramax", layout_files = "../inst/extdata/spectraMax_layout_plate2.csv")
# Format time
df_co2 <- sp_data_layout %>%
  filter(Wells == "C10")

time_test <- sp_data$`Time(hh:mm:ss)`
sp_data_layout$Time_HH <- get_time_in_minutes(time_test)

# log transform of Measurements
sp_data_layout$log_measurements <- log(sp_data$Measurement)

# Calculate growth rate
growth_rate = sp_data_layout %>%
  # first sort by year
  arrange(Wells) %>%
  mutate(Diff_time = Time_HH - lag(Time_HH),  # Difference in time (just in case there are gaps)
         Diff_growth = log_measurements - lag(log_measurements), # Difference 
         Rate = (Diff_growth / (Diff_time + 1))/lag(log_measurements) * 100) # growth rate in percent

gr_test <- growth_rate %>% 
  mutate(Diff_time = ifelse(Time_HH == 0 , NA, Diff_time),
         Diff_growth = ifelse(Time_HH == 0, NA , Diff_growth),
         Rate = ifelse(Time_HH == 0, NA, Rate )
         )

gr_fil <- gr_test %>%
  filter(condition == "glucose")

glc <- gr_fil %>% 
  select(Wells, Time_HH, Rate) %>% 
  spread(Wells,  Rate)

df <- melt(glc ,  id.vars = 'Time_HH', variable.name = 'series')
df_co2 <- df %>%
  filter(series == "C10")
min(df_co2[,4])

ggplot(df, aes(Time_HH, value)) + geom_line(aes(colour = series))

 # Plot each well
ggplot(data = glc, aes(x = Time_HH, y = Rate)) + geom_point() +
    facet_wrap(~Wells)
```

```{r}
Time.Training <- sp_data$`Time(hh:mm:ss)`

sp_data$log_measurements <- log(sp_data$Measurement)

get_time_in_minutes <- function(time.col){
 sapply(strsplit(time.col, ":"), function(x) {
        x <- as.numeric(x)
        if (length(x) <= 2) {
          x[1]/60 + x[2]/3600
        }
        else {
          x[1] + x[2]/60 + x[3]/3600
        }
 })
}

```

```{r}
rolling_summary <- function(DF, time_col, fun, window_size, step_size, min_window=min(DF[, time_col])) {
    # time_col is name of time column
    # fun is function to apply to the subsetted data frames
    # min_window is the start time of the earliest window

    times <- DF[, time_col]

    # window_starts is a vector of the windows' minimum times
    window_starts <- seq(from = min_window, to = max(times), by = step_size)

    # The i-th element of window_rows is a vector that tells us the row numbers of
    # the data-frame rows that are present in window i 
    window_rows <- lapply(window_starts, function(x) { which(times >= x & times < x + window_size) })

    window_summaries <- sapply(window_rows, function(w_r) fun(DF[w_r, ]))
    data.frame(start_time = window_starts, 
               end_time = window_starts + window_size,
               summary = window_summaries)
}

ws <- rolling_summary(DF = df_co2,
                time_col = "Time_HHTime_HHTime_HH",
                fun = function(DF) mean(DF$value),
                window_size = 2,
                step_size = 1,
                min_window = -1)

ggplot(data = ws, aes(x = start_time, y = summary)) + geom_point()
```
