---
title: "Test_layiuot_files"
author: "Martin"
date: "3/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
```

```{r}
data_go <- mpxtractor::read_multiscango_data(file = "../inst/extdata/multiscanGO/multiscanGO_1streading.txt")

data_lyo_go <- mpxtractor::read_layout_files(data = data_go,reader_type = "multiscango", layout_files = "../inst/extdata/multiscanGO/multiscanGO_diauxie_layout.csv", "../inst/extdata/multiscanGO/multiscanGO_diauxie_layout2.csv")

head(data_go)
head(data_lyo_go)
```

```{r}
file = "./inst/extdata/multiscanGO/multiscanGO_1streading.txt"
raw_file <- readLines(file, warn = FALSE, encoding = "latin1")
  raw_file_clean <- raw_file[which(raw_file != "")]  #Remove empty space
  clean_file <- raw_file_clean[-c(1, 2)]  #Remove firs two 
```


```{r}
idx <- grepl("Reading", clean_file)
  #get all the lines whith numbers
  df <- read.table(text = clean_file[!idx])
  #Calculate the number of lines between readings
  wd <- diff(c(which(idx), length(idx) + 1)) - 1
  #Assign reading to corresponding values
  df <- cbind(Reading = rep(clean_file[idx], wd), df)
  df   <- cbind(Well_Row = rep(LETTERS[1:wd[1]], length(wd)), df)
  head(df)
  # Leave only the number of Readings
  num_read <- gsub("\\tReading:", "\\1", df$Reading)
  # Add column reading with the number of reading as numeric
  df$Reading <- as.numeric(num_read)
  df2 <- df[c(-1,-2)]
  colnames(df2) <- 1:ncol(df2)
  df3 <- cbind(df[, c(1,2)], df2)
  
  head(df3)
```

```{r}
df_tmp <- df3 %>% tidyr::gather(Well_Col, Measurement, -c(Well_Row, Reading)) %>%
    dplyr::group_by(Well_Col, Reading) %>%
    dplyr::mutate(rowID = seq_along(Well_Col)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(Wells = interaction(Well_Row, Well_Col, sep = ""),Well_Row = NULL, Well_Col = NULL)

#df_tmp3  <- tidyr::gather(df_tmp, key = "Wells", value = "Measurement", -c(Reading, rowID))
head(df_tmp)
du <- duplicated(df_tmp)
length(du[du == TRUE])

wells <- df_tmp$Wells
  wellsname <- gsub("(^[A-Z])([0-9]$)", "\\10\\2", wells)
  df_tmp$Wells <- wellsname
  df_result <- dplyr::select(df_tmp, Wells, everything(), -rowID)
df_result
```


```{r}
# Main function
read_multiscango_data <- function(file){
  check_one_file_provided(file)
  check_file_path(file)
  check_that_file_is_non_empty(file)
  clean_file <- get_raw_file_clean_multiscango(file)
  df <- format_df(clean_file)
  df_tmp <- add_header(df)
  df_final_format <- final_format_df(df_tmp)
  df_result <- set_well_ids(df_final_format)
  df_result_tidy <- tidyr::as_tibble(df_result)
  df_result_tidy
}
```

```{r}
# get the raw file
get_raw_file_clean_multiscango <- function(file){
  raw_file <- readLines(file, warn = FALSE, encoding = "latin1")
  raw_file_clean <- raw_file[which(raw_file != "")]  #Remove empty space
  clean_file <- raw_file_clean[-c(1, 2)]  #Remove firs two lines
}
```

```{r}
# format_df
format_df <- function(clean_file){
  #Get indx of readings
  idx <- grepl("Reading", clean_file)
  #get all the lines whith numbers
  df <- read.table(text = clean_file[!idx])
  #Calculate the number of lines between readings
  wd <- diff(c(which(idx), length(idx) + 1)) - 1
  #Assign reading to corresponding values
  df <- cbind(Reading = rep(clean_file[idx], wd), df)
  # Leave only the number of Readings
  num_read <- gsub("\\tReading:", "\\1", df$Reading)
  # Add column reading with the number of reading as numeric
  df$Reading <- as.numeric(num_read)
  return(df)
}

```

```{r}
# Header
add_header <- function(df)
{
  df2 <- df[-1]
  colnames(df2) <- LETTERS[1:ncol(df2)]
  df3 <- cbind(Reading = df[, 1], df2)
}
```

```{r}
final_format_df <- function(df3)
{
  df_tmp <- df3 %>% tidyr::gather(Col, Measurement, -Reading) %>%
    dplyr::group_by(Reading, Col) %>%
    dplyr::mutate(rowID = seq_along(Col)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(name = interaction(Col, rowID, sep = ""), Col = NULL, rowID = NULL) %>%
    tidyr::spread(name, Measurement)
  df_tmp2 <- tidyr::gather(df_tmp, key = "Wells", value = "Measurement", -Reading)
}

set_well_ids <- function(df_tmp2)
{
  wells <- df_tmp2$Wells
  wellsname <- gsub("(^[A-Z])([0-9]$)", "\\10\\2", wells)
  df_tmp2$Wells <- wellsname
  df_result <- dplyr::select(df_tmp2, Wells, everything())  #Swap the well column to the first column
}

```

