---
title: "Untitled"
author: "Martin"
date: "3/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

```{r}
data_fl <- mpxtractor::read_spectramax_data(file = "../spectraMAx/data/20190701_growthrates_mg1363_pt2_smA_1stplate.txt")

data_multi <- mpxtractor::read_multiple_files(reader_type = "spectramax", filesname = c("./inst/extdata/spectraMax_1stplate.txt","./inst/extdata/spectraMax_2ndplate.txt"))

lay <-  mpxtractor::read_layout_files(data_fl"../spectraMAx/data/20190611_growthrates_biolog_layout_plate1.csv", reader_type = "spectramax" )
head(datalyout)
```

Full function
```{r}
spMax <- read_multiscango_data(file = "./inst/extdata/multiscanGO_1streading.txt")
```

```{r}

read_multiscango_data <- function(file){
  check_one_file_provided(file)
  check_file_path(file)
  check_that_file_is_non_empty(file)
  clean_file <- get_raw_file_clean_multiscango(file)
  df <- format_df(clean_file)
  df_tmp <- add_header(df)
  df_final_format <- final_format_df(df_tmp)
  df_result <- set_well_ids(df_final_format)
  df_result_tidy <- tidyr::as_tibble(df_result)
  df_result_tidy
}

```

```{r}
check_one_file_provided <- function(file) {
  if (length(file) > 1) {
    stop(paste0(
      "Sorry, only one file should be provided, but you provided ",
      "multiple."
    ), call. = FALSE)
  }
}
```

```{r}
check_file_path <- function(file) {
  if (is.null(file) || !file.exists(file)) {
    stop(paste0("Sorry, can't find your file '", file, "'."),
      call. = FALSE
    )
  }
  if (!(grepl("[Tt][Xx][Tt]$", file))) {
    stop(paste0("Sorry, '", file, "'doesn't have a proper .txt file extension."),
      call. = FALSE
    )
  }
}
```

```{r}
check_that_file_is_non_empty <- function(file) {
  if (length(readLines(file)) == 0) {
    stop(paste0("Sorry, '", file, "' is empty and must not be."),
      call. = FALSE
    )
  }
}
```

```{r}
file = "./inst/extdata/multiscanGO_1streading.txt"

mu <- get_raw_file_clean_multiscango(file)
head(raw_file)
get_raw_file_clean_multiscango <- function(file){
  raw_file <- readLines(file, warn = FALSE, encoding = "latin1")
  raw_file_clean <- raw_file[which(raw_file != "")]  #Remove empty space
  processed_file <- raw_file_clean[-c(1, 2)]  #Remove firs two lines
}
```

```{r}
intermediate_df <- function(processed_file) {
  idx <- grepl("Reading", processed_file)
  df_intermediate <- read.table(text = processed_file[!idx])
  wd <- diff(c(which(idx), length(idx) + 1)) - 1
  # Assign reading to corresponding values
  df_intermediate <- cbind(
    Reading = rep(processed_file[idx], wd),
    df_intermediate
  )

  df_intermediate <- cbind(
    Well_Row = rep(LETTERS[1:wd[1]], length(wd)),
    df_intermediate
  )

  # Leave only the number of Readings from the string
  num_read <- gsub("\\tReading:", "\\1", df_intermediate$Reading)

  df_intermediate$Reading <- as.numeric(num_read)
  return(df_intermediate)
}

````

```{r}
add_header <- function(df_intermediate) {
  df2 <- df_intermediate[c(-1, -2)]
  colnames(df2) <- 1:ncol(df2)
  final_df <- cbind(df_intermediate[, c(1, 2)], df2)
}

```

```{r}
final_format_df <- function(final_df) {
  df_tmp <- final_df %>%
    tidyr::gather(Well_Col, Measurement, -c(Well_Row, Reading)) %>%
    dplyr::group_by(Well_Col, Reading) %>%
    dplyr::mutate(rowID = seq_along(Well_Col)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(
      Wells = interaction(Well_Row, Well_Col, sep = ""),
      Well_Row = NULL,
      Well_Col = NULL
    )
}
```

```{r}

set_well_ids <- function(df_tmp) {
  wells <- df_tmp$Wells
  wellsname <- gsub("(^[A-Z])([0-9]$)", "\\10\\2", wells)
  df_tmp$Wells <- wellsname
  df_result <- df_tmp %>%
    dplyr::select(Wells, everything(), -rowID) %>%
    dplyr::arrange(Reading)
}
```

```{r}


```
