---
title: "plot_layout"
author: "Martin"
date: "3/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
platemap_df <- mpxtractor::read_plate_file(file = file)

platemap <- dplyr::mutate(platemap_df,
                            Row = as.numeric(match(toupper(substr(Wells, 1, 1)),
                                                   LETTERS)),
                            Column = as.numeric(substr(Wells, 2, 5)))


```

Layout spectraMax
```{r}
plot_plate <- mpxtractor::plot_lyout_file(file = "../inst/extdata/spectraMax_layout_plate2.csv", var_shape = "basic", var_colour = "condition", name_plate_layout = "Plate experiment")
plot_plate
```

Layout fluorstar
```{r}
file = "../inst/extdata/fluorstar_test_layout.csv"
                                        
plot_plate <- mpxtractor::plot_lyout_file(file = file_path,
                                          var_shape = "Basic", 
                                          var_colour = "Medium", 
                                          name_plate_layout = "Plate experiment Fluorstar")
plot_plate
```



```{r}
file = "../inst/extdata/fluorstar_test_layout.csv"

platemap_df <- mpxtractor::read_plate_file(file = file)

platemap <- dplyr::mutate(platemap_df,
                            Row = as.numeric(match(toupper(substr(Wells, 1, 1)),
                                                   LETTERS)),
                            Column = as.numeric(substr(Wells, 2, 5)))

n_col <- length(unique(platemap$Column))
n_row <- length(unique(platemap$Row))


ggplot2::ggplot(data = platemap, aes(x = Column, y = Row)) +

  
geom_point(data = expand.grid(seq(1, n_col ), 
                              seq(1, n_row)), 
                              aes(x = Var1, y = Var2),
                              color = "grey39", fill = "white", shape = 21, size = 5) +
scale_y_reverse(breaks = seq(1, n_row), labels=LETTERS[1:n_row]) +
scale_x_continuous(breaks = seq(1, n_col), position = "top") +
labs(title = "Plate Layout for My Experiment") +
geom_point(aes(shape = Basic, colour = Medium), size = 3) +
theme(legend.box = "horizontal", 
      plot.margin = unit(c(1,1,1,1), "cm"),
      text = element_text(size = 10),
      axis.text.x = element_text(angle = 0, hjust = 0.5)) +
scale_colour_viridis_d()
    
```

```{r}
file = "../inst/extdata/fluorstar_test_layout.csv"

platemap_df <- mread_plate_file(file, well_ids_column = "Wells")
platemap_df <- dplyr::mutate(platemap_df,
                            Row = as.numeric(match(toupper(substr(Wells, 1, 1)),
                                                   LETTERS)),
                            Column = as.numeric(substr(Wells, 2, 5)))

ggplot(data = platemap, aes(x = Column, y = Row)) +

geom_point(data = expand.grid(seq(1, 24), seq(1, 16)), aes(x = Var1, y = Var2),
           color = "grey", fill = "white", shape = 21, size = 5) +
  
  
#coord_fixed(ratio = (13/12)/(9/8), xlim = c(0.5, 24), ylim = c(0.5, 16)) +
scale_y_reverse(breaks = seq(1, 16), labels = LETTERS[1:16]) +
scale_x_continuous(breaks = seq(1, 24)) +
scale_colour_viridis_d() +
geom_point(aes(shape = basic, colour = condition ), size = 4) +
#theme_bdc_microtiter(base_size = 10)

theme(legend.box = "horizontal", plot.margin = margin(3, 0, 2, 0, "cm"), 
      legend.title = element_text(colour = "blue", size = 10, face = "bold")) 

```



```{r}
file_path <- file_path_layout <- system.file("extdata",
                                "spectraMax_layout_plate1.csv", 
                                package = "mpxtractor")


plot_layout <- mpxtractor::plot_lyout_file(file = file_path_layout, 
                                           var_shape = "basic" ,
                                           var_colour = "condition", 
                                           name_plate_layout = "My experiment microplate")

plot_layout
```

piechart for dots
```{r}
library(ggplot2)
library(dplyr)
df <- data_frame(x1 = rnorm(5), y1 = rnorm(5)) %>% 
  group_by(x1, y1) %>%
  do(data_frame(component = LETTERS[1:3], value = runif(3))) %>% 
  mutate(total = sum(value)) %>% 
  group_by(x1, y1, total) 

df.grobs <- df %>% 
  do(subplots = ggplot(., aes(1, value, fill = component)))
```


