---
title: "growth_rate_2nd_test"
author: "Martin"
date: "4/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(signal)
```

```{r}
#Read data
sp_data <- mpxtractor::read_spectramax_data(file = "../inst/extdata/spectraMax_2ndplate.txt")
sp_data_layout <- mpxtractor::read_layout_files(sp_data, reader_type = "spectramax", layout_files = "../inst/extdata/spectraMax_layout_plate2.csv")
```

```{r}
# Time in hs
get_time_in_hh <- function(time.col){
 sapply(strsplit(time.col, ":"), function(x){
        x <- as.numeric(x)
        if (length(x) <= 2) {
          x[1]/60 + x[2]/3600
        }
        else {
          x[1] + x[2]/60 + x[3]/3600
        }
 })
}

Time_HH <- get_time_in_hh(sp_data$`Time(hh:mm:ss)`)

# Move column time to the front
sp_data_layout <- cbind(Time_HH, sp_data_layout)

# Clean the dataframe
sp_tidy_data <- sp_data_layout %>%
   select(c(-`Time(hh:mm:ss)`, -`Temperature(°C)`, -Plate))


```





```{r}
# Split data in control and sample
sp_data_control <- dplyr::filter(sp_tidy_data, basic == "control")

sp_data_sample <-dplyr::filter(sp_tidy_data, basic == "sample")
```

```{r}
# Remove faulty data, C18 not filled correctly
sp_data_sample<- dplyr::filter(sp_data_sample, Wells != "C18")
```


```{r}
#### background correction - taking minimum value of each well
sp_data_sample <- sp_data_sample %>%
  group_by(Wells) %>%
  mutate(min_measurement = min(Measurement))

sp_data_sample$bg_corrected <- (sp_data_sample$Measurement - sp_data_sample$min_measurement)
```


```{r}
# Calculate the dt
sp_data_sample <- sp_data_sample %>%
  mutate(Diff_time = Time_HH[2] - Time_HH[1])
# log transform of bg corrected measurements
sp_data_sample$log_measurement <- log(sp_data_sample$bg_corrected)

#replace -inf by NA
is.na(sp_data_sample$log_measurement) <- sapply(sp_data_sample$log_measurement, is.infinite)

impute.mean <- function(x) {
  replace(x, is.na(x), mean(x, na.rm = TRUE))
} 

sp_data_sample %>%
    group_by(Wells) %>%
    mutate(
         log_measurement_impute = impute.mean(log_measurement)
    )

library(imputeTS)
sp_data_sample$impute <- na_ma(sp_data_sample$log_measurement, k = 1)


```


```{r}
# Smooth the data using Savitzky and Golay filter(savgol)
windowsize <- 2 #hs
timestep <- 2/60 # hs
windowlength = (windowsize /sp_data_sample$Diff_time[2])

if ((windowlength %% 2) == 0) {
 windowlength <- windowlength + 1
}
```


```{r}
#is.na(sp_data_sample) <- sapply(sp_data_sample, is.infinite)

sg0 <- sp_data_sample %>%
                   group_by(Wells) %>% 
                   group_map(~ sgolayfilt(.x$impute, 
                                          p = 1,
                                          n = windowlength,
                                          m = 0,
                                          ts = timestep))
sp_data_sample$sg0 <- as.vector(unlist(sg0))

mu <- sp_data_sample %>%
                   group_by(Wells) %>% 
                   group_map(~ sgolayfilt(.x$impute, 
                                          p = 1,
                                          n = windowlength,
                                          m = 1,
                                          ts = timestep))

sp_data_sample$mu <- as.vector(unlist(mu))
```

```{r}

sp_data_sample$offset = sp_data_sample$sg0 - sp_data_sample$mu * sp_data_sample$Time_HH

dmudt <- sp_data_sample %>%
                   group_by(Wells) %>% 
                   group_map(~ sgolayfilt(.x$mu, 
                                          p = 1,
                                          n = windowlength,
                                          m = 1,
                                          ts = timestep))

sp_data_sample$dmudt <- as.vector(unlist(dmudt))
                                                                                                                    
```


```{r}
sp_data_sample <- sp_data_sample %>%
                  group_by(Wells) %>%
                  mutate(max_mu = max(mu))

t <- sp_data_sample %>%
  dplyr::filter(Wells == c("D02","D03","D04","E02","E03","E04", "N02","N03","N04"))

ggplot(data = t, aes(x = Time_HH, y = mu)) +
    facet_wrap(~Wells, drop = FALSE, ncol = 3) +
    geom_line(aes(colour = condition ), size = 1) +
    theme_void()
  
theme_bw() +
        theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "white"))
```
```{r}
spT <- sp_data_sample %>%
  group_by(Wells) %>%
  do(subplots = ggplot(., aes(x = Time_HH, y = mu)) +
  geom_line(aes(colour = condition), size = 1) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.background = element_blank(),
    panel.border = element_rect(colour = "white"))
  )
      

```
```{r}


file = "../inst/extdata/fluorstar_test_layout.csv"

platemap_df <- mpxtractor::read_plate_file(file = file)

platemap <- dplyr::mutate(platemap_df,
                            Row = as.numeric(match(toupper(substr(Wells, 1, 1)),
                                                   LETTERS)),
                            Column = as.numeric(substr(Wells, 2, 5)))

n_col <- length(unique(platemap$Column))
n_row <- length(unique(platemap$Row))


ggplot2::ggplot(data = platemap, aes(x = Column, y = Row)) +
geom_point(data = expand.grid(seq(1, n_col ), 
                              seq(1, n_row)), 
                              aes(x = Var1, y = Var2),
                              color = "grey39", fill = "white", shape = 21, size = 5) +
scale_y_reverse(breaks = seq(1, n_row), labels=LETTERS[1:n_row], expand = c(0.25, 0)) +
scale_x_continuous(breaks = seq(1, n_col), position = "top", expand = c(0.25, 0)) +
labs(title = "Plate Layout for My Experiment") +

geom_point(aes(shape = Basic, colour = Medium), size = 3) +
theme(legend.box = "horizontal", 
      plot.margin = unit(c(1,1,1,1), "cm"),
      text = element_text(size = 10),
      axis.text.x = element_text(angle = 0, hjust = 0.5)) +
scale_colour_viridis_d()
```


```{r}
time <- sp_data_sample$Time_HH
offset <- sp_data_sample$offset
mu <- sp_data_sample$mu
timewindow <- 2

windowstart = time[1] - timewindow / 2
windowend = time[1] + timewindow / 2

selectionmask = (windowstart < sp_data_sample$Time_HH & sp_data_sample$Time_HH < windowend)

truey = sp_data_sample$log_measurement[selectionmask,]

modely = offset + df.loc[selectionmask, 'time'] * mu
SStot = sum((truey - np.mean(truey)) ** 2)
SSres = sum((truey - modely) ** 2)
      try:
        R2 = 1 - SSres / SStot
  except(ZeroDivisionError):
            R2 = np.nan
        store.append(R2)
    df['R2'] = store

```







```{r}
x <- c(rep(0,15), rep(10, 10), rep(0, 15))
sg <- sgolayfilt(x)

```







